name: test

on:
  push

jobs:
  test:
    name: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: config conda and install
        shell: bash -l {0}
        run: |
          conda config --set always_yes True
          conda install --file requirements/run.txt --file requirements/tests.txt pip
          pip install --no-deps -e .

      - name: lint
        shell: bash -l {0}
        run: |
          flake8

      - name: run tests
        shell: bash -l {0}
        run: |
          pytest -v
